services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: rag_lab_postgres
    environment:
      POSTGRES_DB: rag_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag_lab"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: